### ISSUE TITLE
Isochrones for stellar parameters

### ISSUE THREAD

**Issue by alexji** [andycasey/smhr#1]
If no Fe II lines (or if Teff from H-line?): Determine logg from an isochrone given the temperature, propagating temperature uncertainties.

User should input the isochrone (age, metallicity) and ADS reference; we can use Y2 or Dartmouth isochrones as default.

**Comment by andycasey** [comment]
This could be *nearly* trivially included by making use of the ``isochrones`` package.

Having that package would also be convenient for displaying a H-R diagram on the summary tab, but I don't want to *require* the ``isochrones`` package because the associated isochrone grids that are needed can be hundreds of MB or >1GB.

**Comment by alexji** [comment]
The H-R diagram is for logg vs Teff, right? It's probably easiest to store a few Y2 isochrones locally for that.

I've used `isochrones` for another project and it's easy to use, but it takes a lot of disk space and is still a bit under development. It may be best to not lump the isochrone functionality into SMH, but rather make a separate (small) package that builds on `isochrones` and prints the results and/or creates a file that can be imported into SMH.

**Comment by alexji** [comment]
I'm closing this, we are not going to do it in SMHR.
