### ISSUE TITLE
fitting advice?

### ISSUE THREAD

**Issue by maddiecain** [andycasey/smhr#203]
When I press "Fit Model" when working on synthesis, almost every time I press it the abundance updates to a new number, even when I haven't changed any of the [X/Fe] values. Is this how it's supposed to be working? If so, should I just press "Fit Model" a few times until it stops updating and stays at a constant value?

**Comment by alexji** [comment]
This is a generic problem on all syntheses. I'm closing this for now because indeed the problem just tends to be that the fit has not converged in the number of iterations allowed. Since the real solution is hard to solve and the practical solution is just to fit multiple times, I think this is in the "not-worth-fixing" category.

Note that we don't really want the fit to go to  completion necessarily, because e.g. it autofits when you mask the spectrum, and you don't want that to take too long.
