### ISSUE TITLE
Synthesis elements are all loaded twice, once in I and in II.

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#204]
![bildschirmfoto 2016-08-15 um 12 58 27](https://cloud.githubusercontent.com/assets/19806342/17672362/0190ff20-62ea-11e6-8adb-a24d4a674962.png)

**Comment by alexji** [comment]
This is fixed in v0.2 with the new "master list" importing. In this, when you import a synthesis list, you can say what the wavelength/species/expot/loggf for the line should be. Then it will only be associated with one species.

Otherwise if you import one synth on the fly it will continue to be like this, but I expect that will be rare with the new setup.
