### ISSUE TITLE
Method to find out what abundance needs to be changed for fit

### ISSUE THREAD

**Issue by mgull19** [andycasey/smhr#206]
Right now if I want to find out which element a line is, I have to change each abundance in the abundance table tab individually until I find out which one it is. 
Anna said that in the old smh there was a different way to do it.

**Comment by alexji** [comment]
This is a thing we need to do. It won't be implemented in the current master version (v0.1) because I have not refactored the code, but I will include it in v0.2.

I think it would be nice to also do have a similar option during the EQW fitting, i.e. have other EW lines marked in addition to the one you're fitting.

**Comment by alexji** [comment]
In v0.2, when you click on an element in the abundance table it draws a blue line above the location of the line in the spectrum (rv corrected). I have even put in a division between "strong" and "weak" lines (just a hardcoded expot/loggf cut).
