### ISSUE TITLE
Exception raised: too many values to unpack

### ISSUE THREAD

**Issue by HonggeunKim** [andycasey/smhr#283]
An exception was encountered in [this session](https://transfer.sh/zCSvw/session.smh) using version None on Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) [GCC 7.2.0]:

````python
Traceback (most recent call last):

  File "/home/honggeun/smhr-master/smh/gui/linelist_manager.py", line 976, in import_transitions
    N = self.session.import_transitions(path)

  File "/home/honggeun/smhr-master/smh/session.py", line 318, in import_transitions
    line_list, spectral_model_states = pickle.load(fp)

ValueError: too many values to unpack
````

Below is a screenshot from the application at the time that the exception occurred:

![screenshot](https://transfer.sh/1U9gv/screenshot.png)

**Additional details on how this exception occurred**:

**Comment by alexji** [comment]
This is probably due to importing the wrong thing; use import transitions
after you've exported previously measured transitions from SMHR.
If you want to add synthesis linelists or equivalent width linelists, use
those buttons instead.

I will close this issue after having SMHR create a useful error message...

**Comment by alexji** [comment]
This was an older version of SMH and has now been fixed when import_transitions was refactored
